---
title: "2020_43_Great_American_Beer_Festival_Data"
author: "Eric Fletcher"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
library(tidytuesdayR)
library(tidyverse)
library(forcats)
library(tidytext)
library(glue)
theme_set(theme())
```
```{r Data Import}

tuesdata <- tidytuesdayR::tt_load(2020, week = 43)

# View data dictionary
tuesdata

beer_awards <- tuesdata$beer_awards

view(beer_awards)
```

```{r Main Data Changes}
beer_awards_tidy <- beer_awards %>%
  # Reorder the factor levels
  mutate(medal = fct_relevel(medal, c("Gold", "Silver", "Bronze")))
  

```
The data set includes 1,859 breweries over 34 years from 1987 to 2020.
```{r Counts}
beer_awards_tidy %>% 
  count(year)

beer_awards_tidy %>% 
  count(brewery)


```

```{r Total Medals per State}
# Total medals per state for states with >9 total medals.

beer_awards_tidy %>% 
  count(medal, state, name = "total_medals") %>%
  mutate(state =  reorder_within(state, total_medals, medal)) %>%
  filter(total_medals >= 10) %>% 
  ggplot(aes(x = state, y = total_medals)) +
  geom_text(aes(label = total_medals, hjust = 0), size = 3) +
  geom_col() + 
  facet_wrap(~ medal, scales = "free") +
  coord_flip() +
  scale_x_reordered() +
  expand_limits(y = 400) + 
  labs(title = "Great American Beer Festival",
       subtitle = "Total Medals per State, 1987 - 2020",
       x = "State",
       y = "Total Medals",
       caption = "Data: The Great American Beer Festival"
  )
```

```{r Total Medals per Category}
#Total medals per category for categories with >13 total medals. 
beer_awards_tidy %>% 
  count(category, medal, sort = TRUE) %>% 
  mutate(category = reorder_within(category, n, medal)) %>% 
  filter(n > 13) %>% 
  ggplot(aes(x = category, y = n)) +
  geom_text(aes(label = n, hjust = 0), size = 3) +
  geom_col() +
  facet_wrap(~ medal, scales = "free") +
  coord_flip() +
  scale_x_reordered() +
  expand_limits(y = 30) + 
  labs(title = "Great American Beer Festival",
       subtitle = "Total Medals per Category, 1987 - 2020",
       x = "",
       y = "Total Medals (n > 13)"
  )
```

```{r Total Number of Beers Over Time}
# Total number of awards over time. 
beer_awards_tidy %>%
  group_by(year) %>% 
  summarise(total = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = year, y = total)) +
  geom_line() +
  expand_limits(y = 0) +
  labs(title = "Great American Beer Festival",
       subtitle = "Total Number of Awarded Beers Over Time, 1987 - 2020",
       x = "Year",
       y = "Total Medals",
       color = "Medal")



# Total number of awarded beers over time by medal type.
beer_awards_tidy %>%
  group_by(year, medal) %>% 
  summarise(total = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = year, y = total)) +
  geom_line(aes(color = medal), size = 1.5) +
  expand_limits(y = 0) +
  scale_color_manual(values = c("#FFD700", "#C0C0C0", "#cd7f32")) +
  labs(title = "Great American Beer Festival",
       subtitle = "Total Number of Awarded Beers Over Time by Medal Type, 1987 - 2020",
       x = "Year",
       y = "Total Medals",
       color = "Medal")
```
```{r Top Breweries - TidyTuesday}

# Top 20 breweries by total medals.
brewery_top_20 <- beer_awards_tidy %>% 
  group_by(brewery, state) %>% 
  summarise(n = n()) %>% 
  ungroup() %>% 
  slice_max(order_by = n, n = 20) %>%
  mutate(brewery = glue("{ brewery }, { state }")) %>%
  view() %>% 
  pull(brewery)
  
# Plot 
beer_awards_tidy %>% 
  mutate(brewery = glue("{ brewery }, { state }")) %>%
  filter(brewery %in% brewery_top_20) %>%
  group_by(brewery, medal) %>%
  summarise(total_medals = n()) %>%
  ungroup() %>%
  ggplot(aes(x = reorder(brewery, total_medals), y = total_medals, fill = medal)) +
  geom_bar(stat = "identity", width = 0.8) + 
  geom_text(aes(x = reorder(brewery, total_medals), y = total_medals, label = total_medals), position = position_stack(vjust = 0.5)) +
  coord_flip() +
  scale_fill_manual(values = c("#FFD700", "#C0C0C0", "#cd7f32")) +
  labs(
    title = "The Great American Beer Festival",
    subtitle = "Top Breweries by Total Medals, 1987 - 2020",
    x = "Brewery",
    y = "Medals",
    caption = "Data: The Great American Beer Festival",
    fill = ""
  ) +
  theme(
    plot.title = element_text(size = 15),
    axis.text = element_text(size = 11),
    legend.text = element_text(size = 10),
    axis.title = element_text(size = 13)
  )
```





