---
title: "European Energy"
author: "Eric Fletcher"
date: "8/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidytuesdayR)
library(tidyverse)
library(skimr)
library(scales)
library(janitor)
theme_set(theme_light())
```
```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 32)
tuesdata$energy_types
```
```{r}
energy_types <- tuesdata$energy_types
country_totals <- tuesdata$country_totals
```
```{r}
skim(energy_types)
```
```{r}
options(scipen = 999)
#create tibble to left_join and use with coalesce to input country_name values where they're currently NA (EL, UK)
country_map <- tibble(country = c("EL", "UK"),
                      country_name_na_replace = c("Greece", "UK"))

energy_types_clean <- energy_types %>%
#left_join above tibble to include all rows 
  left_join(country_map, by = "country") %>% 
#coalesce to account for NA values in country column. Use case_when to replace country_name values that did not match how they are used in europe_countries_grid2 in the geoFacet package
  mutate(country_name = coalesce(country_name, country_name_na_replace),
         country_name = case_when(country_name == "Bosnia & Herzegovina" ~ "Bosnia & H.",
                                  country_name == "North Macedonia" ~ "N. Macedonia",
                                  TRUE ~ country_name)) %>% 
  select(-country_name_na_replace, -level) %>% 
  pivot_longer(cols = 4:6, names_to = "year") %>% 
  pivot_wider(names_from = type, values_from = value) %>%
  clean_names() %>% 
  rowwise() %>% 
  mutate(grand_total = sum(conventional_thermal, nuclear, hydro, 
                           pumped_hydro_power, wind, solar, geothermal, other),
                           across(where(is.numeric), ~ 100 * . / grand_total)) %>% 
  pivot_longer(cols = conventional_thermal:other, 
               names_to = "type", values_to = "percent") %>% 
  mutate(type = case_when(type == "conventional_thermal" ~ "Conventional Thermal",
                          type == "nuclear" ~ "Nucelar",
                          TRUE ~ "Renewable"))

bar <- energy_types_clean %>%
  ggplot(aes(x=year, y=percent, fill = type)) +
  geom_bar(stat = "identity", position = "stack", width = 0.5)+
  scale_fill_manual(values = c("#ff0000", "#CCFF00", "#00d7ff"))+
  scale_y_continuous(breaks = seq(0,100,25), labels = paste0(seq(0,100,25)*1,"%"))+
  facet_wrap(~country_name, scales = "free")+
  #facet_geo(~country_name, grid = "europe_countries_grid2", scales = "free")+
  coord_flip()+
  theme_minimal()+
    theme(plot.background = element_rect(fill = "#30332E"),
    text = element_text(color = "white"),
    strip.text = element_text(color = "white"),
    strip.text.x = element_text(size = 20),
    panel.grid = element_blank(),
    axis.text.x = element_text(color = "white", size = 14),
    axis.text.y = element_text(color = "white", size = 14),
    plot.margin = unit(c(2, 2, 2, 2), "cm"),
    legend.position = c(0.84, .055),
    legend.title = element_text(size = 27),
    legend.text = element_text(size = 20),
    plot.title = element_text(size = 50, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 25, hjust = 0.5),
    plot.caption = element_text(color = "white", size = 21)) +
  labs(
    x = "",
    y = "",
    fill = "Energy Production Type",
    title = "European Energy Generation",
    subtitle = "Share of Total by Production Type",
    caption = "Data: Eurostat Energy | Visualization: Eric Fletcher"
  )

ggsave(bar, 
       units = c("in"),
       width = 24,
       height = 19,
       dpi = 300, 
       file="2020_32_EuropeanEnergy.png", 
       type="cairo-png")
```



