---
title: "Plants in Danger"
author: "Eric Fletcher"
date: "8/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggtext)
library(showtext)
font_add_google("Noto Serif TC", "Noto Serif TC")
showtext_auto()
theme_set(theme_minimal())

```

```{r data import}
#data import from the TidyTuesday GitHub page
tuesdata <- tidytuesdayR::tt_load(2020, week = 34)

#data dictionary for plants.csv, threats.csv, actions.csv
tuesdata

#rename data set to something that is easier to manage
plants <- tuesdata$plants

view(plants)

plants %>% 
  count(continent)
```

```{r EDA}
#convert year_last_seen column to factor class
plants$year_last_seen <- as.factor(plants$year_last_seen)

#inspect the levels
levels(plants$year_last_seen)

#reorder the levels so Before 1900 is first
plants$year_last_seen <- factor(plants$year_last_seen, levels = c("Before 1900", "1900-1919",   "1920-1939", "1940-1959", "1960-1979", "1980-1999", "2000-2020"))

#adding color to caption
```


```{r EDA}
mycaption <- 'Data: IUCN Red List | Visualization: Eric Fletcher | <span style="color:red;">**#SavethePlants**</span>'

#plot red_list_category totals for each year
bar <- plants %>% 
  na.omit() %>% 
  group_by(year_last_seen, red_list_category) %>% 
  summarise(total = n()) %>% 
  ggplot(aes(x = year_last_seen, y = total, fill = red_list_category))+
  geom_col(position = "dodge") +
  geom_text(aes(label = total), position = position_dodge(width = 1), vjust = -0.2, size = 7)+
  scale_fill_manual(values = c("#ff0000", "#cccc00"))+
  expand_limits(y = seq(0, 125, 25))+
  labs(title ="Plants in <strong><span style='color:#ff0000'>**Danger**</span></strong></b>",
       subtitle = "Global Totals by Period",
       caption = mycaption,
       x = "",
       y = "",
       fill = "")+
  theme(plot.margin = unit(c(1,1,1,1), "cm"),
        legend.position = "bottom",        
        plot.title = element_markdown(
          family = "Noto Serif TC",
          hjust = 0.5,
          size = 30
        ),
        plot.subtitle = element_text(
          family = "Noto Serif TC",
          hjust = 0.5,
          size = 12
        ),
        plot.caption = element_markdown(
          family = "Noto Serif TC",
          hjust = 0.5,
          size = 12
        ),
        axis.text.y = element_blank(),
        axis.text.x = element_text(family = "Noto Serif TC",
                                   size = 16),
        legend.text = element_text(family = "Noto Serif TC",
                                   size = 14),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        legend.key.size = unit(.7,"line"))
bar

ggsave(bar, 
       units = c("in"),
       width = 4,
       height = 3,
       dpi = 300, 
       file="2020_34_PlantsinDanger_Custom.png", 
       type="cairo-png")
```







