---
title: "2020_9_MeaslesVaccination"
author: "Eric Fletcher"
date: "8/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(scales)
library(skimr)
library(showtext) #did not use
font_add_google("", "")
theme_set(theme_light())
```
```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 9)
measles <- tuesdata$measles
```
```{r}
skim(measles)
```
### What is the mean vaccination rate for each state?
```{r}
#summary table prior to plotting
measles_grand_mean <- measles %>%
  filter(mmr >= 0) %>% 
  mutate(grand_mean = mean(mmr), na.rm = TRUE) %>%
  group_by(state, grand_mean) %>% 
  summarise(mean_state = mean(mmr, na.rm = TRUE))
  pull(grand_mean)
```
### Let's plot the results!
```{r}
bar <- measles %>% 
  filter(mmr > 0) %>% 
  ggplot(aes(x = reorder(state, mmr), y = mmr, color = state)) +
  geom_jitter(width = 0.3, size = 1, alpha = 0.06) +
  stat_summary(fun = mean, geom = "point", size = 2, alpha = .9, color = "black")+
  geom_hline(data = measles_grand_mean, aes(yintercept = grand_mean), color = "black", size = 0.6) +
  geom_segment(data = measles_grand_mean, aes(x = state, xend = state, y = mean_state, yend = grand_mean),
               color = "black", size = 0.2)+                                                                                   
  coord_flip()+
  scale_y_continuous(breaks = seq(0,100,25), labels = paste0(seq(0,100,25), "%"))+
  labs(title = "School's Measles, Mumps, and Rubella (MMR) Vaccination Rate by State",
       subtitle = "State Mean (black point) and Grand Mean (horizontal line) Provided",
       caption = "Data: The Wall Street Journal | Visualization: Eric Fletcher",
       x="",
       y="")+
  theme(plot.title = element_text(
          #family = "",
          hjust = 0.5,
          face = "bold",
          size = 10, 
          color = "black"),
        plot.subtitle = element_text(
          #family = "",
          hjust = 0.5,
          face = "bold",
          size = 7, 
          color = "black"),
       plot.caption = element_text(
         family = "",
          hjust = 0.5,
          face = "bold",
          size = 6, 
          color = "black"),
        legend.position = "none",

        axis.text.y = element_text(color = "black", size = 7),
        axis.text.x = element_text(color = "black", size = 7),
        plot.margin = unit(c(2, 2, 2, 2), "cm"))

ggsave(bar, 
       units = c("in"),
       width = 8,
       height = 5.5,
       dpi = 300, 
       file="2020_31_Measles.png", 
       type="cairo-png")
```