---
title: "2020_35_Chopped"
author: "Eric Fletcher"
date: "8/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import libraries}
library(tidyverse)
library(tidytuesdayR)
library(tidytext)
library(stringr)
library(ggwordcloud)
library(wordcloud)
library(tidyr)
library(scales)
library(svglite)
```

```{r import data}
#//reading in the data with tidytuesdayR package
tuesdata <- tidytuesdayR::tt_load(2020, week = 35)

tuesdata

chopped <- tuesdata$chopped
```

```{r tidying}
tidy_chopped <- chopped %>% 
  select(appetizer, entree, dessert) %>% 
  pivot_longer(cols = c(appetizer, entree, dessert), names_to = "meal", values_to = "ingredients") %>% 
  unnest_tokens(word, ingredients, token = str_split, pattern = ", ")

tidy_chopped$meal <- factor(tidy_chopped$meal, levels = c("appetizer", "entree", "dessert"))
levels(tidy_chopped$meal) <- c("Appetizer", "Entree", "Dessert")

set.seed(2020)
bar <- tidy_chopped %>%
  filter(!is.na(word)) %>% 
  group_by(word) %>% 
  count(word, meal, sort = TRUE) %>% 
  filter(n > 5) %>% 
  ggplot(aes(label = word, size = n))+
  geom_text_wordcloud_area(aes(color = meal)) +
  scale_color_manual(values = c("#A81812", "#D36D2F", "#F5A73C"))+
  facet_wrap(~meal) +
  theme_minimal() +
  labs(title ="Chopped",
       subtitle = "Most Common Main Ingredient Across 45 Seasons by Course",
       caption = "Data: Kaggle | Visualization: Eric Fletcher")+
  theme(plot.margin = unit(c(1,1,1,1), "cm"),
        #strip.text.x = element_text(color = )
        plot.title = element_text(
          #family = "Noto Serif TC",
          hjust = 0.5,
          size = 30,
          #color = "#8B6A3B",
          #face = "bold"
        ),
        plot.subtitle = element_text(
          #family = "Noto Serif TC",
          hjust = 0.5,
          size = 10
        ),
        plot.caption = element_text(
          #family = "Noto Serif TC",
          hjust = 0.5,
          size = 8
        ))
bar
ggsave(bar, 
       units = c("in"),
       width = 10,
       height = 3.9,
       dpi = 300, 
       file="2020_35_Chopped.png", 
       type="cairo-png")

```
<<<<<<< HEAD

=======
>>>>>>> 4daa56a7156094af81f1c9f83e1b9b76b3f1022c
