---
title: "Untitled"
author: "Eric Fletcher"
date: "9/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
library(stringr)
library(ggrepel)
```

```{r}
options(scipen = 999)

state_spending <- read.csv("/Users/ericfletcher/Desktop/PK12ed_real.csv")
state_spending

# Remove the X prefix from column names
colnames(state_spending) <- sub("X", "", colnames(state_spending))
state_spending

k12_perchild <- read.csv("/Users/ericfletcher/Desktop/PK12ed_realperch.csv")
k12_perchild

# Remove the X prefix from column names
colnames(k12_perchild) <- sub("X", "", colnames(k12_perchild))
k12_perchild
```

```{r}
state_spending_long <- state_spending %>% 
  pivot_longer(cols = 2:21, names_to = "year", values_to = "spending")

state_spending_long$year <- as.integer(state_spending_long$year)
state_spending_long

k12_perchild_long <- k12_perchild %>% 
  pivot_longer(cols = 2:21, names_to = "year", values_to = "spending")

k12_perchild_long$year <- as.integer(k12_perchild_long$year)
k12_perchild_long <- k12_perchild_long %>% 
  filter(state != "District of Columbia")
```
```{r}
k12_perchild_long

# summary statistics
k12_summary <- k12_perchild_long %>% 
  mutate(state = reorder(state, -spending),
         grand_mean = mean(spending, na.rm = TRUE)) %>% 
  group_by(state, grand_mean) %>% 
  summarise(mean_per_state = mean(spending, na.rm = TRUE))

bar <- k12_perchild_long %>%
  group_by(state, year, spending) %>% 
  ggplot(aes(x=reorder(state, spending), y = spending))+
  stat_summary(fun = mean, geom = "point", size = 1.4, alpha = 1)+
  geom_hline(aes(yintercept = 6.32717), color = "red", size = 0.6)+
  geom_segment(data = k12_summary,
               aes(x = state, xend = state, y = mean_per_state, yend = grand_mean), size = 0.9)+
  coord_flip() +
  labs(title = "Public spending on elementary and secondary education",
       subtitle = "Average spent per child ages 0-18 by state, 1997 - 2016",
       x = "",
       y = "Spending in $1,000s",
       caption = "Data: Isaacs, Lauderback, Greenberg, 2020 | Visualization: Eric Fletcher") +
  theme(plot.background = element_rect(fill = "#e3e3e3"),
        panel.background = element_rect(fill = "#e3e3e3"))+
#adding curve, see arrow coordinates above for data
  geom_curve(
    data = arrows, aes(x = x1, y = y1, xend = x2, yend = y2),
    arrow = arrow(length = unit(0.07, "inch")), size = 0.4,
    color = "gray20", curvature = -0.3
  ) +
##ARROOW PLACEMENT
#add text
      annotate(
        "text", x = 26, y = 8, size = 3, color = "red", lineheight = .8,
        label = glue::glue("Horizontal Line:\n Grand Mean")) +
      annotate(
        "text", x = 31.4, y = 5, size = 3, color = "red", lineheight = .8,
        label = glue::glue("Points:\n State Mean"))

ggsave(bar, 
       units = c("in"),
       width = 10,
       height = 6.9,
       dpi = 300, 
       file="education_spending.png", 
       type="cairo-png")
  
  
arrows <-
  tibble(
    x1 = c(25, 30),
    x2 = c(20, 25),
    y1 = c(8, 5),
    y2 = c(6.32717, 6)
  )
```



```{r}
library(ggplot2)
library(ggalt)
theme_set(theme_classic())

health <- read.csv("https://raw.githubusercontent.com/selva86/datasets/master/health.csv")
health
health$Area <- factor(health$Area, levels=as.character(health$Area))  # for right ordering of the dumbells

# health$Area <- factor(health$Area)
gg <- ggplot(health, aes(x=pct_2013, xend=pct_2014, y=Area, group=Area)) + 
        geom_dumbbell(color="#a3c4dc", 
                      size=0.75, 
                      point.colour.l="#0e668b") + 
        scale_x_continuous(label=percent) + 
        labs(x=NULL, 
             y=NULL, 
             title="Dumbbell Chart", 
             subtitle="Pct Change: 2013 vs 2014", 
             caption="Source: https://github.com/hrbrmstr/ggalt") +
        theme(plot.title = element_text(hjust=0.5, face="bold"),
              plot.background=element_rect(fill="#f7f7f7"),
              panel.background=element_rect(fill="#f7f7f7"),
              panel.grid.minor=element_blank(),
              panel.grid.major.y=element_blank(),
              panel.grid.major.x=element_line(),
              axis.ticks=element_blank(),
              legend.position="top",
              panel.border=element_blank())
gg
```
```{r}
state_dumbell <- state_spending %>% 
  select(state, "1997", "2016") %>% 
  ggplot(aes(x = 1997, xend = 2016, y = state)) +
  geom_dumbbell(color="#a3c4dc", 
                      size=0.75, 
                      point.colour.l="#0e668b") + 
  scale_x_continuous(label=comma) + 
  labs(x=NULL, 
       y=NULL, 
       title="Dumbbell Chart", 
       subtitle="Pct Change: 2013 vs 2014", 
       caption="Source: https://github.com/hrbrmstr/ggalt") +
  theme(plot.title = element_text(hjust=0.5, face="bold"),
        plot.background=element_rect(fill="#f7f7f7"),
        panel.background=element_rect(fill="#f7f7f7"),
        panel.grid.minor=element_blank(),
        panel.grid.major.y=element_blank(),
        panel.grid.major.x=element_line(),
        axis.ticks=element_blank(),
        legend.position="none",
        panel.border=element_blank())

state_dumbell
```
